// Generated by Airplane, do not edit:
// https://app.airplane.dev/t/hello_world
import airplane from "airplane";

export default async function (params) {
  airplane.output(`Hello, ${params.name}`);
}
