// Generated by Airplane, do not edit:
// https://app.airplane.dev/t/hello_world

import airplane from "airplane";

type Params = {
  name: string;
};

export default async function (params: Params) {
  airplane.output(`Hello, ${params.name}!`);
}
